# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment', models.IntegerField()),
                ('reapeat_times', models.IntegerField()),
                ('time_type', models.CharField(max_length=100)),
                ('repeating', models.CharField(max_length=10)),
                ('minigoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.MiniGoal')),
            ],
        ),
    ]
