# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20170201_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='minigoal',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
            preserve_default=False,
        ),
    ]
