# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_minigoal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='minigoal',
            name='finished_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minigoal',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
