# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20170201_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='minigoal',
            name='note',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
