# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_minigoal_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
